### ISSUE TITLE
Ansible 2 for Configuration Management, Video 1.4

### ISSUE THREAD

**Issue by devopsdymyr** [PacktPublishing/Ansible-2-for-Configuration-Management#2]
Hi ,
I have some issue on the video 1.4 .i have mentioned all details in the attached image.

i have ansible in my aws ubuntu ec2 instace and on the the instance followed your steps.
i am able to provision 3 vms in aws which is working fine

![image](https://user-images.githubusercontent.com/41105507/66997060-6858a280-f0ef-11e9-936f-102ddc478682.png)

**Comment by AlanHohn** [comment]
Hello,

This is what I mean in the `README.md` by, "look at the variables in group_vars/all.yaml to make sure they match your configuration (especially the location of your SSH private key)." Sorry that wasn't clearer.

You can try commenting out that line in `group_vars/all.yaml` to see if the default SSH key will work. If not, modify it to refer to the location of the `.pem` file that you are using to successfully log in to your three EC2 machines.

Unfortunately private keys like this are hard to make identical for everyone.
